src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore.Irc/Configuration/BotConfig.cs
src/SpikeCore/SpikeCore.Irc/IIrcClient.cs
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore.Web/appsettings.json
src/SpikeCore/SpikeCore/Bot.cs
src/SpikeCore/SpikeCore/SpikeCore.csproj

* Add `IConfiguration` to container as a singleton
* Add `Bot` block to `appsettings.json` with values previously in `IrcClient.cs`
* Introduce a `BotConfig` type to encapsulate our IRC configuration
* Add a dependency on `Microsoft.Extensions.Configuration.Binder` in `SpikeCore` so we can bind BotConfig
* Percolate the bot config down our callstack
There are a couple of sharp edges, but we'll be taking another pass later to refactor our IoC/DI solution that should address most of them.

Move hard-coded IRC configuration parameters to appsettings.json

---

src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore.Irc/IIrcClient.cs
src/SpikeCore/SpikeCore.Web/Services/BotManager.cs
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore/Bot.cs

* All `IService` instances are now added as Singletons instead of Transient: we should only have one instance of these
* Stop passing around `IService` to dependencies
* `BotManager` now takes an `IBot` instead of an `IServiceProvider`
* `Bot` now takes an `IIrcClient` instead of an `IServiceProvider`
* Dependencies are now injected instead of pulled from the app context
* We no longer pass around `IConfiguration` to our bot
* Binding is now done in `Startup`
* We now register `BotConfig` with the service provider
* Remove a few properties/backing fields we no longer need
* Remove a few of the locks around various `Connect` methods
* This is where we were pulling from our `IServiceProvider`
* Our dependencies are now injected via the container
* A side effect is that it may be possible to …

Tighten up our dependency injection/configuration

---

src/SpikeCore/SpikeCore.Messages/SpikeCore.Messages/IrcConnectMessage.cs
src/SpikeCore/SpikeCore.Messages/SpikeCore.Messages/IrcReceiveMessage.cs
src/SpikeCore/SpikeCore.Messages/SpikeCore.Messages/IrcSendMessage.cs
src/SpikeCore/SpikeCore.Messages/SpikeCore.Messages/SpikeCore.Messages.csproj
src/SpikeCore/SpikeCore.Web/Hubs/TestHub.cs
src/SpikeCore/SpikeCore.Web/Services/BotManager.cs
src/SpikeCore/SpikeCore.Web/Services/IBotManager.cs
src/SpikeCore/SpikeCore.Web/SpikeCore.Web.csproj
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore.sln
src/SpikeCore/SpikeCore/Bot.cs
src/SpikeCore/SpikeCore/IBot.cs
src/SpikeCore/SpikeCore/SpikeCore.csproj

- Removes Rebus: we're swapping to Foundatio. Rebus has some issues with nested context (i.e. publishing from a consumer), and Foundatio seems more tailored towards what we're doing.
- Provides a Foundatio version of @AndyCJ's `messagebus-first-pass` branch.
We're going to want to fix the subscription, but @AndyCJ will do that in a followup commit.

Replace rebus with foundatio

---

src/SpikeCore/SpikeCore.Messages/SpikeCore.Messages/IMessageHandler.cs
src/SpikeCore/SpikeCore.Web/AutofacFoundatio/ContainerBuilderExtensions.cs
src/SpikeCore/SpikeCore.Web/Services/BotManager.cs
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore/Bot.cs

Added ContainerBuilderExtensions which has a RegisterFoundatio method for configuring Foundatio and Autofac for auto-wiring IMessageHandler<> instances.
Added IMessageHandler<>.
Changed Bot and BotManager to wrie up thier message subscribing via IMessageHandler<> rather than IMessageBus.
The ExpressionTree code could be replaced with some "simpler" reflection based code, but it works and it's not that bad, so I've left it in.

Auto-wiring for message bus subscriptions using AutoFac and Foundatio.

---

src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore.Web/appsettings.json
src/SpikeCore/SpikeCore/Irc/Configuration/ModuleConfiguration.cs
src/SpikeCore/SpikeCore/Modules/AboutModule.cs
src/SpikeCore/SpikeCore/Modules/HelpModule.cs
src/SpikeCore/SpikeCore/Modules/IModule.cs
src/SpikeCore/SpikeCore/Modules/ModuleBase.cs

* Introduces a new ModuleConfiguration section.
* This has a prefix trigger for now (defaults to `~` like SpikeLite)
* The ModuleConfiguration is injected into ModuleBase
* Adds IModule and BaseModule as our preliminary abstractions
* IModule requires properties for the module name, description, and instructions
* These are in turn used by ModuleBase to do some quick routing, and by the HelpModule to provide help
* ModuleBase implements ` IMessageHandler<IrcChannelMessageMessage>` out of the box and does some dispatching based on module name
* This should help reduce boilerplate
* We'll also do authorization here when we have it
* ModuleBase does not expose the injected MessageBus out of the box, but instead provides primitives for sending messages
* We do not have the ability to set the …

Add a preliminary module system:

---

src/SpikeCore/SpikeCore/Modules/FactoidModule.cs
src/SpikeCore/SpikeCore/Modules/ModuleBase.cs

* ModuleBase will default this to be the `Name` property
* This means anyone not defining a custom trigger will use the module name (e.g. about, help)
* Or, for things like Factoids, we can use custom triggers (e.g. idiot, warn, ban)
* These are a prefix: ModuleBase will do `startsWith(triggerPrefix + trigger)` where the prefix is from your config (default: `~`)
* This is done in an `Any()` across all potential triggers

Adds a new `Triggers` property to ModuleBase

---

src/SpikeCore/SpikeCore.Irc.Irc4NetButSmarter/IrcClient.cs
src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore.Web/appsettings.json
src/SpikeCore/SpikeCore/Irc/Configuration/IrcConnectionConfig.cs
src/SpikeCore/SpikeCore/Irc/IIrcClient.cs
src/SpikeCore/SpikeCore/Irc/IrcClientBase.cs
src/SpikeCore/SpikeCore/Irc/IrcConnection.cs

* Port NickServ identification from SpikeLite
* Adds two new `IrcConnection` settings:
* `Authenticate` - set to `true` if you want to authenticate with network services
* `Password` - the password to use when authenticating with network services, if `Authenticate` is set to `true`
We probably also want to port over something that'll wait for confirmation from services before joining channels from SpikeLite. But bed for now...

Add network services authentication:

---

src/SpikeCore/SpikeCore.Irc.Irc4NetButSmarter/IrcClient.cs
src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore/Irc/IrcClientBase.cs

* If authenticate is set to `true` in your config, the bot will now block on NickServ telling you that you've identified before joining channels
* If it's set to `false`, the bot will join channels as soon as it's connected to a network
* `JoinChannel` is now a first-class method on `IrcClient`, which we'll probably want for admin commands (join/part/quit etc)
* The enumeration of channels to join in `IrcClient` is now private, since implementing classes only need to implement `JoinChannel`
* Both `IrcClient` implementations will now act on `NOTICE` as well as `PRIVMSG` - though we're not piping the former to the web UI yet

Port "join after identification behavior" from SpikeLite:

---

src/SpikeCore/SpikeCore.Irc.Irc4NetButSmarter/IrcClient.cs
src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore/Irc/IIrcClient.cs
src/SpikeCore/SpikeCore/Irc/IrcClientBase.cs
src/SpikeCore/SpikeCore/Irc/IrcConnection.cs
src/SpikeCore/SpikeCore/Irc/PrivMessage.cs
src/SpikeCore/SpikeCore/MessageBus/IrcPrivMessage.cs
src/SpikeCore/SpikeCore/MessageBus/IrcSendPrivateMessage.cs
src/SpikeCore/SpikeCore/Modules/AboutModule.cs
src/SpikeCore/SpikeCore/Modules/FactoidModule.cs
src/SpikeCore/SpikeCore/Modules/HelpModule.cs
src/SpikeCore/SpikeCore/Modules/KarmaModule.cs
src/SpikeCore/SpikeCore/Modules/ModuleBase.cs

* Inbound PRIVMSG collapsed: the same event/message will handle both public and private PRIVMSG
* It is almost never the case that the bot would care about the source of the message (public vs. private)
* The behavior to handle the event will be the same - except for emitting a reply
* This is actually a tad bit closer to the spec
* `ChannelMessage` renamed to `PrivMessage`, `IrcChannelMessageMessage` renamed to `IrcPrivMessage`
* Added a `Private` boolean property to `IrcPrivMessage` to make it easier to determine if this is 1:1 or 1:n
* This is a shortcut that checks to see if the message has a channel target
* Added a `SendPrivateMessage` method to `IIrcClient` to handle actual sending of 1:1 PRIVMSG
* This will send a new `IrcSendPrivateMessage` message
* `IrcConnection` has an …

Add PM support to the bot:

---

src/SpikeCore/SpikeCore.Irc.Irc4NetButSmarter/IrcClient.cs
src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore.Web/Program.cs
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore/Domain/WebHostCancellationTokenHolder.cs
src/SpikeCore/SpikeCore/Irc/IIrcClient.cs
src/SpikeCore/SpikeCore/Irc/IrcClientBase.cs
src/SpikeCore/SpikeCore/Irc/IrcConnection.cs
src/SpikeCore/SpikeCore/MessageBus/IrcJoinChannelMessage.cs
src/SpikeCore/SpikeCore/MessageBus/IrcPartChannelMessage.cs
src/SpikeCore/SpikeCore/MessageBus/IrcQuitMessage.cs
src/SpikeCore/SpikeCore/Modules/AdminModule.cs
src/SpikeCore/SpikeCore/Modules/FactoidModule.cs
src/SpikeCore/SpikeCore/Modules/ModuleBase.cs

* Supports quit, join, and part right now
* Requires the "Admin" role
* Adds corresponding methods to the `IIrcClient` and `IrcClientBase`
* Our IoC container is now aware of a `WebHostCancellationTokenHolder`
* This wraps  he `CancellationTokenSource` that our `WebHost` is watching to shut down the app
* We need this so that our "quit" commands will kill the bot entirely
* This is injected into the `IrcClientBase` to be used in implementations of `Quit`
* `Startup` now calls `PropertiesAutowired()` on our `IrcClient` singleton
* The `WebHost` configured in `Program` registers our `WebHostCancellationTokenHolder` because it's the only thing with enough context

Add an "admin" module:

---

src/SpikeCore/SpikeCore.Irc.Irc4NetButSmarter/IrcClient.cs
src/SpikeCore/SpikeCore.Irc.IrcDotNet/IrcClient.cs
src/SpikeCore/SpikeCore/Irc/IrcClientBase.cs

* Add a `HandleDisconnect` event handler to `IrcClientBase`
* This handles a generic retry loop, making use of a few things the inheriting classes need to implement
* `UnwireEvents` prevents certain IRC clients from colliding things like MOTD handlers on reconnect.
* It does what it says on the tin: it unwires all events that `Connect` wires up
* Add an `IsConnected` to prevent infinite retry loops, this is defined by the client with a property body
* Added a no-arg `Connect`: this does the actual meat of reconnection, and is called by the argful constructor and reconnect handling
* Calling `quit` now sets a var that short circuits the retry loop
This is more or less equivalent to what we were doing in SpikeLite

Port reconnection from SpikeLite

---

src/SpikeCore/SpikeCore.Web/Program.cs
src/SpikeCore/SpikeCore.Web/SpikeCore.Web.csproj
src/SpikeCore/SpikeCore.Web/appsettings.json
src/SpikeCore/SpikeCore/Irc/IrcClientBase.cs
src/SpikeCore/SpikeCore/SpikeCore.csproj

* Adds dependencies on Serilog:
* Serilog at 2.7.1
* Serilog.AspNetCore at 2.1.1
* Serilog.Sinks.Console at 3.1.1
* Serilog.Settings.Configuration at 2.6.1
* Wired up to use `appsettings.json` (with `reloadOnChange` set to true) to configure logging
* The logger has a property-based enrichment for `App Name` set to `Spikecore`
* The default logging will set the minimum level at `Debug`, but a threshold on Microsoft at `Information` because it's spammy
* The default format of log statements is overriden to always use UTC
* An example log line: `[2019-01-25 14:40:24Z INF] Running, press CTRL-C to stop the bot.`
* Swap out calls to `Console.WriteLine` with appropriate logging

Swap from using default logging to Serilog:

---

src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore.Web/appsettings.json
src/SpikeCore/SpikeCore/Irc/Configuration/ModuleConfiguration.cs
src/SpikeCore/SpikeCore/Modules/GeoIpModule.cs
src/SpikeCore/SpikeCore/Modules/KarmaModule.cs
src/SpikeCore/SpikeCore/Modules/ModuleBase.cs
src/SpikeCore/SpikeCore/SpikeCore.csproj

* Uses `ipstack.com` as the GeoIP vendor for now.
* It provides a free registration tier with a decent amount of queries per month
* Seems to be reliable and well recommended
* Optionally enriches the GeoIP lookup with a score from getipintel.net
* This requires that you give them a valid contact email, but is otherwise free at 2 queries/sec
* Minimal checking against known TOR nodes seems like it's not completely insane
* Adds two new module configurations in appsettings.json:
* `GeoIpApiKey` - register a free one at ipstack.com, slap it in here
* `GeoIpIntelEmailAddress` - this is, as it implies, an email. Slap it in here to use the optional security score enrichment
* If `GeoIpIntelEmailAddress` is undefined, you can still get location results as long as you provide `GeoIpApiKey`
* If …

Add GeoIP support to the bot

---

src/SpikeCore/SpikeCore.Web/SpikeCore.Web.csproj
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore.Web/appsettings.json
src/SpikeCore/SpikeCore/Irc/LoggingListener.cs

* Adds a new LoggingListener. Right now it's just logging PRIVMSG at the `Information` level
* Uses templatized types so wen can search within Seq more easily
* Drop Microsoft log level to `Warning`: doesn't seem to be much useful at the `Information` level
* Add a dependency for `Serilog.Sinks.Seq` at `4.0.0`
* This means you can optionally add a `WriteTo` block for `Seq` in your appsettings.json block for `Serilog`

Logging Part 2:

---

src/SpikeCore/SpikeCore/Modules/FactoidModule.cs

* Remove the word "factoids" from the help string - this shouldn't be here (copy/paste from SpikeLite)
* Proper case the module `Name` property to match other modules

Fix help for `factoids` module:

---

src/SpikeCore/SpikeCore/Data/Models/SpikeCoreUser.cs
src/SpikeCore/SpikeCore/Modules/AdminModule.cs
src/SpikeCore/SpikeCore/Modules/UserManagementModule.cs

* list/show/add/remove
* Handles the ASP.NET Core Identity nuances (users + roles as well as the logins, which delegate auth to network services)
* This is admin only
* This should hopefully help make it easier to add/remove explicit users, so we can deprecate the "shared" user
* Adds an `isAdmin` method to the `SpikeCoreUser` to reduce copy/paste for checking if users are administrators

Add user management administrative commands:

---

src/SpikeCore/SpikeCore.Web/Configuration/WebConfig.cs
src/SpikeCore/SpikeCore.Web/Startup.cs
src/SpikeCore/SpikeCore.Web/appsettings.json

* Adds a `PathBase` property to the `Web` section in `appsettings.json`
* This will set the `PathBase` if non-empty
* This allows for "trimming" proxies, that redirect from `/foo/bar` -> `/bar`
* Handy for dealing with nginx as a reverse proxy
* Is equivalent to prefixing all paths with the PathBase (i.e. `/Account` becomes `/foo/Account`)
* Add configuration to respect `X-Forwarded-For` and `X-Forwarded-For-Proto`

Add ability for the bot to run behind a reverse proxy

---

.github/workflows/dotnet-core.yml

Create a GH Action YAML file that we can use to replace Travis CI
* Runs on `master`, and pull requests to `master`
* Docker build now runs on all branches, but only pushes on `master`
* Otherwise functionally identical
This closes #50.

Add a GitHub Action to do basic CI

---

.github/workflows/dotnet-core.yml

* Update GH Actions configuration to point to `liberacsharp/spikecore`
instead of `freenodecsharp/spikecore`
close #58

GH-58: Point build to new DockerHub account

---

.github/workflows/dotnet-core.yml

* Should now publish both a `linux/amd64` and a `linux/arm64` flavored Docker image
* Move from `docker/build-push-action@v1`  to `docker/build-push-action@v2`
* Uses the `docker/setup-qemu-action@v1` step to build ARM64 images
* Also uses the new `docker/login-action@v1` to obtain credentials
* Will still use the same push logic (GitHub event is `push`, and the ref is `refs/heads/master`)
* Will still push the same tag (`liberacsharp/spike_core:latest`)
Closes #61

GH-61: Publish ARM64 Docker image
